- hosts: all
  vars:
    wifi_countrycode: DE
    wifi_ssid: <SSID>
    wifi_password: <PASSWORD>
    devices:
    - 192.168.178.21 # Speakers
    controllers:
    - 192.168.178.20 # MBP
    - 192.168.178.40 # iPhone
  roles:
  - {role: 'security'}
  - {role: 'bridge'}
  - {role: 'teufelhole'}